# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow3):
        MainWindow3.setObjectName("MainWindow3")
        MainWindow3.resize(409, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 20, 401, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.opacityLabel = QtWidgets.QLabel(self.frame)
        self.opacityLabel.setGeometry(QtCore.QRect(20, 20, 360, 470))
        self.opacityLabel.setStyleSheet("background-color: rgba(0, 0, 0, 165);\n"
"border-radius: 20px;")
        self.opacityLabel.setText("")
        self.opacityLabel.setObjectName("opacityLabel")
        self.menuTitleLabel = QtWidgets.QLabel(self.frame)
        self.menuTitleLabel.setGeometry(QtCore.QRect(130, 50, 151, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.menuTitleLabel.setFont(font)
        self.menuTitleLabel.setStyleSheet("color: rgba(255, 255, 255, 210);")
        self.menuTitleLabel.setObjectName("menuTitleLabel")
        self.signupButton = QtWidgets.QPushButton(self.frame)
        self.signupButton.setGeometry(QtCore.QRect(100, 380, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.signupButton.setFont(font)
        self.signupButton.setStyleSheet("QPushButton#signupButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 5, 20, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#signupButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 5, 20, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#signupButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 220)\n"
"}")
        self.signupButton.setObjectName("signupButton")
        self.userLine = QtWidgets.QLineEdit(self.frame)
        self.userLine.setGeometry(QtCore.QRect(100, 210, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userLine.setFont(font)
        self.userLine.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 3px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, 230);\n"
"padding-bottom: 7px;")
        self.userLine.setObjectName("userLine")
        self.passwordLine = QtWidgets.QLineEdit(self.frame)
        self.passwordLine.setGeometry(QtCore.QRect(100, 280, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordLine.setFont(font)
        self.passwordLine.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 3px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, 230);\n"
"padding-bottom: 7px;")
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.nameLine = QtWidgets.QLineEdit(self.frame)
        self.nameLine.setGeometry(QtCore.QRect(100, 130, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLine.setFont(font)
        self.nameLine.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 3px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, 230);\n"
"padding-bottom: 7px;")
        self.nameLine.setObjectName("nameLine")
        MainWindow3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 409, 26))
        self.menubar.setObjectName("menubar")
        MainWindow3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow3)
        self.statusbar.setObjectName("statusbar")
        MainWindow3.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

    def retranslateUi(self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow3", "MainWindow"))
        self.menuTitleLabel.setText(_translate("MainWindow3", "SIGN UP"))
        self.signupButton.setText(_translate("MainWindow3", "SIGN UP"))
        self.userLine.setPlaceholderText(_translate("MainWindow3", "User"))
        self.passwordLine.setPlaceholderText(_translate("MainWindow3", "Password"))
        self.nameLine.setPlaceholderText(_translate("MainWindow3", "Name"))
